modLoader="javafml"
loaderVersion="[41,)"
license="MIT License"
[[mods]]
modId="harderfarther"
version="${file.jarVersion}"
displayName="Harder Farther Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harderfarther"
updateJSONURL="https://github.com/mactso/harderfarther/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Farther Mod.'
[[dependencies.harderfarther]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderfarther]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
