modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
[[mods]]
modId="harderfarther"
version="${file.jarVersion}"
displayName="Harder Farther Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harderfarther"
updateJSONURL="https://github.com/mactso/harderfarther/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Farther Mod.'
[[dependencies.harderfarther]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderfarther]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.harderfarther]]
    modId="terrablender"
    mandatory=true
    versionRange="[1.20.1-3.0.0.164,)"
    ordering="NONE"
    side="BOTH"
